apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-depl
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
      - name: job-service
        image: job-service:latest
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "development"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-srv:5672"
        - name: REDIS_HOST
          value: job-redis-srv
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: job-srv
  labels:
    app: job-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: job-service

