apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
stringData:
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  RECAPTCHA_SECRET_KEY: your-super-secret-recaptcha-key-change-in-production
